// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSgX2y-um5TIl5GBO6yE9MZnxmO6xQ9Ao',
    appId: '1:559850230380:web:a2a1bc64d4369465ab3e49',
    messagingSenderId: '559850230380',
    projectId: 'miro-b6680',
    authDomain: 'miro-b6680.firebaseapp.com',
    storageBucket: 'miro-b6680.firebasestorage.app',
    measurementId: 'G-9NP239T4YN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCL8S5os2PvS3qlN4mg3sQbBs9Pj1KvS9M',
    appId: '1:559850230380:android:33a772f9245ee96dab3e49',
    messagingSenderId: '559850230380',
    projectId: 'miro-b6680',
    storageBucket: 'miro-b6680.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApAvE6sQPXxsQMr_PMTun_crQMLAW03BQ',
    appId: '1:559850230380:ios:3f4714abed602b0eab3e49',
    messagingSenderId: '559850230380',
    projectId: 'miro-b6680',
    storageBucket: 'miro-b6680.firebasestorage.app',
    iosClientId: '559850230380-kvec23hi88s9dno4frl6jh2bk4cimd10.apps.googleusercontent.com',
    iosBundleId: 'com.example.miro',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyApAvE6sQPXxsQMr_PMTun_crQMLAW03BQ',
    appId: '1:559850230380:ios:3f4714abed602b0eab3e49',
    messagingSenderId: '559850230380',
    projectId: 'miro-b6680',
    storageBucket: 'miro-b6680.firebasestorage.app',
    iosClientId: '559850230380-kvec23hi88s9dno4frl6jh2bk4cimd10.apps.googleusercontent.com',
    iosBundleId: 'com.example.miro',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDSgX2y-um5TIl5GBO6yE9MZnxmO6xQ9Ao',
    appId: '1:559850230380:web:374a741407abb6d5ab3e49',
    messagingSenderId: '559850230380',
    projectId: 'miro-b6680',
    authDomain: 'miro-b6680.firebaseapp.com',
    storageBucket: 'miro-b6680.firebasestorage.app',
    measurementId: 'G-714DCR9H5G',
  );
}
